version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/gradle-plugin"
    schedule:
      interval: "weekly"
    groups:
      gradle:
        patterns:
          - "*"
